# Generated by Django 3.1.7 on 2021-11-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Municipio', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=1000)),
                ('Correo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('Metodologia', models.CharField(max_length=100)),
                ('Especialidad', models.CharField(max_length=100)),
                ('ambulatorio', models.CharField(max_length=10)),
                ('hospitalario', models.CharField(max_length=10)),
                ('unidad_movil', models.CharField(max_length=10)),
                ('domiciliario', models.CharField(max_length=10)),
                ('horario_lunes', models.CharField(max_length=60)),
                ('horario_martes', models.CharField(max_length=60)),
                ('horario_miercoles', models.CharField(max_length=60)),
                ('horario_jueves', models.CharField(max_length=60)),
                ('horario_viernes', models.CharField(max_length=60)),
                ('horario_sabado', models.CharField(max_length=60)),
                ('horario_domingo', models.CharField(max_length=60)),
            ],
        ),
    ]
