# Generated by Django 3.2.9 on 2021-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Municipio', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=1000)),
                ('Correo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('Metodologia', models.CharField(max_length=100)),
                ('Especialidad', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=50)),
                ('Longitude', models.CharField(max_length=50)),
            ],
        ),
    ]
